### ISSUE TITLE
Migration ra-core 2.6.4 -> 2.8.5

### ISSUE THREAD

**Issue by kopax** [bootstrap-styled/ra-ui#16]
`@bootstrap-styled/ra-ui` is almost compatible `2.8.5` on [branch migration-ra-2.8.5](https://github.com/bootstrap-styled/ra-ui/tree/migration-ra-2.8.5)

### In order to merge, we need to fix the following issue:

After updating our backoffice app to `2.8.5`, application launches fine but crashes displaying `Resource` lists (in our case, `users`, `projects`, `organizations`). 

```bash
browser.js:34 Uncaught Invariant Violation: [React Intl] An `id` must be provided to format a message.
    at invariant (http://localhost:2000/static/js/13.chunk.js:128107:15)
    at formatMessage (http://localhost:2000/static/js/13.chunk.js:241344:51)
    at translate (http://localhost:2000/static/js/13.chunk.js:100531:23)
    at FieldTitle (http://localhost:2000/static/js/13.chunk.js:195144:93)
    at renderWithHooks (http://localhost:2000/static/js/13.chunk.js:225483:22)
    at mountIndeterminateComponent (http://localhost:2000/static/js/13.chunk.js:227639:17)
    at beginWork (http://localhost:2000/static/js/13.chunk.js:228274:20)
    at performUnitOfWork (http://localhost:2000/static/js/13.chunk.js:232318:16)
    at workLoop (http://localhost:2000/static/js/13.chunk.js:232359:28)
    at HTMLUnknownElement.callCallback (http://localhost:2000/static/js/13.chunk.js:212180:18)
    at Object.invokeGuardedCallbackDev (http://localhost:2000/static/js/13.chunk.js:212229:20)
    at invokeGuardedCallback (http://localhost:2000/static/js/13.chunk.js:212283:35)
    at replayUnitOfWork (http://localhost:2000/static/js/13.chunk.js:231542:9)
    at renderRoot (http://localhost:2000/static/js/13.chunk.js:232472:17)
    at performWorkOnRoot (http://localhost:2000/static/js/13.chunk.js:233396:11)
    at performWork (http://localhost:2000/static/js/13.chunk.js:233306:11)
    at performSyncWork (http://localhost:2000/static/js/13.chunk.js:233280:7)
    at requestWork (http://localhost:2000/static/js/13.chunk.js:233135:9)
    at scheduleWork (http://localhost:2000/static/js/13.chunk.js:232948:9)
    at Object.enqueueSetState (http://localhost:2000/static/js/13.chunk.js:223629:9)
    at Connect.push../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:2000/static/js/13.chunk.js:318413:20)
    at Connect.onStateChange (http://localhost:2000/static/js/13.chunk.js:306330:16)
    at Object.notify (http://localhost:2000/static/js/13.chunk.js:307001:21)
    at Subscription.notifyNestedSubs (http://localhost:2000/static/js/13.chunk.js:307038:20)
    at Connect.onStateChange (http://localhost:2000/static/js/13.chunk.js:306327:16)
    at Object.notify (http://localhost:2000/static/js/13.chunk.js:307001:21)
    at Subscription.notifyNestedSubs (http://localhost:2000/static/js/13.chunk.js:307038:20)
    at Connect.onStateChange (http://localhost:2000/static/js/13.chunk.js:306327:16)
    at Object.dispatch (http://localhost:2000/static/js/13.chunk.js:332853:7)
    at e (<anonymous>:1:40553)
    at http://localhost:2000/static/js/13.chunk.js:308265:18
    at http://localhost:2000/static/js/13.chunk.js:199209:16
    at http://localhost:2000/static/js/13.chunk.js:330574:22
    at dispatch (http://localhost:2000/static/js/13.chunk.js:332384:18)
    at http://localhost:2000/static/js/13.chunk.js:332253:12
    at http://localhost:2000/static/js/13.chunk.js:331170:52
    at exec (http://localhost:2000/static/js/13.chunk.js:331882:5)
    at flush (http://localhost:2000/static/js/13.chunk.js:331925:5)
    at asap (http://localhost:2000/static/js/13.chunk.js:331897:5)
    at runPutEffect (http://localhost:2000/static/js/13.chunk.js:331166:60)
    at runEffect (http://localhost:2000/static/js/13.chunk.js:331109:280)
    at next (http://localhost:2000/static/js/13.chunk.js:330979:9)
    at currCb (http://localhost:2000/static/js/13.chunk.js:331062:7)
invariant @ browser.js:34
formatMessage @ index.es.js:952
translate @ TranslationProvider.js:49
FieldTitle @ FieldTitle.js:15
renderWithHooks @ react-dom.development.js:13450
mountIndeterminateComponent @ react-dom.development.js:15606
beginWork @ react-dom.development.js:16241
performUnitOfWork @ react-dom.development.js:20285
workLoop @ react-dom.development.js:20326
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
replayUnitOfWork @ react-dom.development.js:19509
renderRoot @ react-dom.development.js:20439
performWorkOnRoot @ react-dom.development.js:21363
performWork @ react-dom.development.js:21273
performSyncWork @ react-dom.development.js:21247
requestWork @ react-dom.development.js:21102
scheduleWork @ react-dom.development.js:20915
enqueueSetState @ react-dom.development.js:11596
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:336
onStateChange @ connectAdvanced.js:245
notify @ Subscription.js:29
notifyNestedSubs @ Subscription.js:66
onStateChange @ connectAdvanced.js:242
notify @ Subscription.js:29
notifyNestedSubs @ Subscription.js:66
onStateChange @ connectAdvanced.js:242
dispatch @ createStore.js:175
e @ VM28:1
(anonymous) @ middleware.js:13
(anonymous) @ formMiddleware.js:39
(anonymous) @ middleware.js:72
dispatch @ applyMiddleware.js:46
(anonymous) @ utils.js:282
(anonymous) @ proc.js:557
exec @ scheduler.js:20
flush @ scheduler.js:63
asap @ scheduler.js:35
runPutEffect @ proc.js:553
runEffect @ proc.js:496
next @ proc.js:366
currCb @ proc.js:449
Promise.then (async)
resolvePromise @ proc.js:515
runCallEffect @ proc.js:584
runEffect @ proc.js:496
next @ proc.js:366
currCb @ proc.js:449
checkEffectEnd @ proc.js:689
chCbAtKey @ proc.js:707
currCb @ proc.js:449
(anonymous) @ proc.js:567
exec @ scheduler.js:20
flush @ scheduler.js:63
asap @ scheduler.js:35
(anonymous) @ channel.js:215
emit @ channel.js:39
(anonymous) @ middleware.js:74
(anonymous) @ bindActionCreators.js:3
UnconnectedListController.updateData @ ListController.js:287
UnconnectedListController.componentDidMount @ ListController.js:193
commitLifeCycles @ react-dom.development.js:18115
commitAllLifeCycles @ react-dom.development.js:19674
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:19898
(anonymous) @ react-dom.development.js:21446
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:21445
performWorkOnRoot @ react-dom.development.js:21368
performWork @ react-dom.development.js:21273
performSyncWork @ react-dom.development.js:21247
requestWork @ react-dom.development.js:21102
scheduleWork @ react-dom.development.js:20915
enqueueSetState @ react-dom.development.js:11596
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:336
update @ react-loadable.esm.js:588
(anonymous) @ react-loadable.esm.js:598
Promise.then (async)
_loadModule @ react-loadable.esm.js:597
componentWillMount @ react-loadable.esm.js:545
callComponentWillMount @ react-dom.development.js:11852
mountClassInstance @ react-dom.development.js:11950
updateClassComponent @ react-dom.development.js:15266
beginWork @ react-dom.development.js:16265
performUnitOfWork @ react-dom.development.js:20285
workLoop @ react-dom.development.js:20326
renderRoot @ react-dom.development.js:20406
performWorkOnRoot @ react-dom.development.js:21363
performWork @ react-dom.development.js:21273
performSyncWork @ react-dom.development.js:21247
interactiveUpdates$1 @ react-dom.development.js:21532
interactiveUpdates @ react-dom.development.js:2268
dispatchInteractiveEvent @ react-dom.development.js:5086
Show 49 more frames
3index.js:1437 The above error occurred in the <FieldTitle> component:
    in FieldTitle (created by pure(FieldTitle))
    in pure(FieldTitle) (created by Context.Consumer)
    in translate(pure(FieldTitle)) (created by DatagridHeaderCell)
    in th (created by Th)
    in Th (created by DatagridHeaderCell)
    in DatagridHeaderCell (created by Context.Consumer)
    in translate(DatagridHeaderCell) (created by shouldUpdate(translate(DatagridHeaderCell)))
    in shouldUpdate(translate(DatagridHeaderCell)) (created by Datagrid)
    in tr (created by Tr)
    in Tr (created by Datagrid)
    in thead (created by Thead)
    in Thead (created by Datagrid)
    in table (created by TableUnstyled)
    in TableUnstyled (created by Context.Consumer)
    in StyledComponent (created by Table)
    in Table (created by Datagrid)
    in Datagrid (created by UserList)
    in div (created by ListView)
    in div (created by CardUnstyled)
    in CardUnstyled (created by Context.Consumer)
    in StyledComponent (created by CardContent)
    in CardContent (created by ListView)
    in div (created by ListView)
    in ListView (created by UnconnectedListController)
    in UnconnectedListController (created by Context.Consumer)
    in translate(UnconnectedListController) (created by Connect(translate(UnconnectedListController)))
    in Connect(translate(UnconnectedListController))
    in Unknown (created by List)
    in List (created by UserList)
    in UserList (created by LoadableComponent)
    in LoadableComponent (created by WithPermissions)
    in WithPermissions (created by Connect(WithPermissions))
    in Connect(WithPermissions) (created by getContext(Connect(WithPermissions)))
    in getContext(Connect(WithPermissions)) (created by Route)
    in Route (created by Resource)
    in Switch (created by Resource)
    in Resource (created by Connect(Resource))
    in Connect(Resource)
    in Route (created by RoutesWithLayout)
    in Switch (created by RoutesWithLayout)
    in RoutesWithLayout (created by Route)
    in div (created by Context.Consumer)
    in StyledComponent (created by Layout__Content)
    in Layout__Content (created by Layout)
    in main (created by Context.Consumer)
    in StyledComponent (created by Layout__ContentWithSidebar)
    in Layout__ContentWithSidebar (created by Layout)
    in div (created by Context.Consumer)
    in StyledComponent (created by Layout__LayoutFrame)
    in Layout__LayoutFrame (created by Layout)
    in div (created by Context.Consumer)
    in StyledComponent (created by Layout__LayoutWrapper)
    in Layout__LayoutWrapper (created by Layout)
    in Layout (created by Route)
    in Route (created by withRouter(Layout))
    in withRouter(Layout) (created by Connect(withRouter(Layout)))
    in Connect(withRouter(Layout)) (created by LayoutWithTheme)
    in MuiThemeProvider (created by LayoutWithTheme)
    in LayoutWithTheme (at Layout.js:6)
    in CustomLayout (created by WithPermissions)
    in div (created by Context.Consumer)
    in StyledComponent (created by UtilityProvider)
    in UtilityProvider (created by BootstrapProvider)
    in ThemeProvider (created by BootstrapProvider)
    in BootstrapProvider (created by ConnectedBootstrapProvider)
    in ConnectedBootstrapProvider (created by Connect(ConnectedBootstrapProvider))
    in Connect(ConnectedBootstrapProvider) (created by WithPermissions)
    in AppContextProvider (created by WithPermissions)
    in WithPermissions (created by Connect(WithPermissions))
    in Connect(WithPermissions) (created by getContext(Connect(WithPermissions)))
    in getContext(Connect(WithPermissions)) (created by ComponentWithKopaxLayout)
    in ComponentWithKopaxLayout (created by Connect(ComponentWithKopaxLayout))
    in Connect(ComponentWithKopaxLayout) (created by Route)
    in Route (created by CoreAdminRouter)
    in Switch (created by CoreAdminRouter)
    in div (created by CoreAdminRouter)
    in CoreAdminRouter (created by Connect(CoreAdminRouter))
    in Connect(CoreAdminRouter) (created by getContext(Connect(CoreAdminRouter)))
    in getContext(Connect(CoreAdminRouter)) (created by Route)
    in Route (created by CoreAdminBase)
    in Switch (created by CoreAdminBase)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by CoreAdminBase)
    in TranslationProviderView (created by InjectIntl(TranslationProviderView))
    in InjectIntl(TranslationProviderView) (created by TranslationProvider)
    in IntlProvider (created by TranslationProvider)
    in TranslationProvider (created by Connect(TranslationProvider))
    in Connect(TranslationProvider) (created by CoreAdminBase)
    in Provider (created by CoreAdminBase)
    in CoreAdminBase (created by withContext(CoreAdminBase))
    in withContext(CoreAdminBase) (created by CoreKopaxAdmin)
    in IntlPolyfill (created by CoreKopaxAdmin)
    in CoreKopaxAdmin (at App.js:67)
    in App (at src/index.js:7)

React will try to recreate this component tree from scratch using the error boundary you provided, Layout.
console.<computed> @ index.js:1437
logCapturedError @ react-dom.development.js:17880
logError @ react-dom.development.js:17916
callback @ react-dom.development.js:18973
callCallback @ react-dom.development.js:17104
commitUpdateEffects @ react-dom.development.js:17144
commitUpdateQueue @ react-dom.development.js:17134
commitLifeCycles @ react-dom.development.js:18147
commitAllLifeCycles @ react-dom.development.js:19674
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:19898
(anonymous) @ react-dom.development.js:21446
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:21445
performWorkOnRoot @ react-dom.development.js:21368
performWork @ react-dom.development.js:21273
performSyncWork @ react-dom.development.js:21247
requestWork @ react-dom.development.js:21102
scheduleWork @ react-dom.development.js:20915
enqueueSetState @ react-dom.development.js:11596
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:336
onStateChange @ connectAdvanced.js:245
notify @ Subscription.js:29
notifyNestedSubs @ Subscription.js:66
onStateChange @ connectAdvanced.js:242
notify @ Subscription.js:29
notifyNestedSubs @ Subscription.js:66
onStateChange @ connectAdvanced.js:242
dispatch @ createStore.js:175
e @ VM28:1
(anonymous) @ middleware.js:13
(anonymous) @ formMiddleware.js:39
(anonymous) @ middleware.js:72
dispatch @ applyMiddleware.js:46
(anonymous) @ utils.js:282
(anonymous) @ proc.js:557
exec @ scheduler.js:20
flush @ scheduler.js:63
asap @ scheduler.js:35
runPutEffect @ proc.js:553
runEffect @ proc.js:496
next @ proc.js:366
currCb @ proc.js:449
Promise.then (async)
resolvePromise @ proc.js:515
runCallEffect @ proc.js:584
runEffect @ proc.js:496
next @ proc.js:366
currCb @ proc.js:449
checkEffectEnd @ proc.js:689
chCbAtKey @ proc.js:707
currCb @ proc.js:449
(anonymous) @ proc.js:567
exec @ scheduler.js:20
flush @ scheduler.js:63
asap @ scheduler.js:35
(anonymous) @ channel.js:215
emit @ channel.js:39
(anonymous) @ middleware.js:74
(anonymous) @ bindActionCreators.js:3
UnconnectedListController.updateData @ ListController.js:287
UnconnectedListController.componentDidMount @ ListController.js:193
commitLifeCycles @ react-dom.development.js:18115
commitAllLifeCycles @ react-dom.development.js:19674
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:19898
(anonymous) @ react-dom.development.js:21446
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:21445
performWorkOnRoot @ react-dom.development.js:21368
performWork @ react-dom.development.js:21273
performSyncWork @ react-dom.development.js:21247
requestWork @ react-dom.development.js:21102
scheduleWork @ react-dom.development.js:20915
enqueueSetState @ react-dom.development.js:11596
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:336
update @ react-loadable.esm.js:588
(anonymous) @ react-loadable.esm.js:598
Promise.then (async)
_loadModule @ react-loadable.esm.js:597
componentWillMount @ react-loadable.esm.js:545
callComponentWillMount @ react-dom.development.js:11852
mountClassInstance @ react-dom.development.js:11950
updateClassComponent @ react-dom.development.js:15266
beginWork @ react-dom.development.js:16265
performUnitOfWork @ react-dom.development.js:20285
workLoop @ react-dom.development.js:20326
renderRoot @ react-dom.development.js:20406
performWorkOnRoot @ react-dom.development.js:21363
performWork @ react-dom.development.js:21273
performSyncWork @ react-dom.development.js:21247
interactiveUpdates$1 @ react-dom.development.js:21532
interactiveUpdates @ react-dom.development.js:2268
dispatchInteractiveEvent @ react-dom.development.js:5086
Show 51 more frames
index.js:1437 [React Intl] Missing message: "Invariant Violation: [React Intl] An `id` must be provided to format a message." for locale: "en"
console.<computed> @ index.js:1437
defaultErrorHandler @ index.es.js:666
formatMessage @ index.es.js:976
translate @ TranslationProvider.js:49
Error @ Error.js:57
renderWithHooks @ react-dom.development.js:13450
mountIndeterminateComponent @ react-dom.development.js:15606
beginWork @ react-dom.development.js:16241
performUnitOfWork @ react-dom.development.js:20285
workLoop @ react-dom.development.js:20326
renderRoot @ react-dom.development.js:20406
performWorkOnRoot @ react-dom.development.js:21363
performWork @ react-dom.development.js:21273
performSyncWork @ react-dom.development.js:21247
requestWork @ react-dom.development.js:21102
scheduleWork @ react-dom.development.js:20915
enqueueSetState @ react-dom.development.js:11596
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:336
onStateChange @ connectAdvanced.js:245
notify @ Subscription.js:29
notifyNestedSubs @ Subscription.js:66
onStateChange @ connectAdvanced.js:242
notify @ Subscription.js:29
notifyNestedSubs @ Subscription.js:66
onStateChange @ connectAdvanced.js:242
dispatch @ createStore.js:175
e @ VM28:1
(anonymous) @ middleware.js:13
(anonymous) @ formMiddleware.js:39
(anonymous) @ middleware.js:72
dispatch @ applyMiddleware.js:46
(anonymous) @ utils.js:282
(anonymous) @ proc.js:557
exec @ scheduler.js:20
flush @ scheduler.js:63
asap @ scheduler.js:35
runPutEffect @ proc.js:553
runEffect @ proc.js:496
next @ proc.js:366
currCb @ proc.js:449
Promise.then (async)
resolvePromise @ proc.js:515
runCallEffect @ proc.js:584
runEffect @ proc.js:496
next @ proc.js:366
currCb @ proc.js:449
checkEffectEnd @ proc.js:689
chCbAtKey @ proc.js:707
currCb @ proc.js:449
(anonymous) @ proc.js:567
exec @ scheduler.js:20
flush @ scheduler.js:63
asap @ scheduler.js:35
(anonymous) @ channel.js:215
emit @ channel.js:39
(anonymous) @ middleware.js:74
(anonymous) @ bindActionCreators.js:3
UnconnectedListController.updateData @ ListController.js:287
UnconnectedListController.componentDidMount @ ListController.js:193
commitLifeCycles @ react-dom.development.js:18115
commitAllLifeCycles @ react-dom.development.js:19674
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:19898
(anonymous) @ react-dom.development.js:21446
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:21445
performWorkOnRoot @ react-dom.development.js:21368
performWork @ react-dom.development.js:21273
performSyncWork @ react-dom.development.js:21247
requestWork @ react-dom.development.js:21102
scheduleWork @ react-dom.development.js:20915
enqueueSetState @ react-dom.development.js:11596
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:336
update @ react-loadable.esm.js:588
(anonymous) @ react-loadable.esm.js:598
Promise.then (async)
_loadModule @ react-loadable.esm.js:597
componentWillMount @ react-loadable.esm.js:545
callComponentWillMount @ react-dom.development.js:11852
mountClassInstance @ react-dom.development.js:11950
updateClassComponent @ react-dom.development.js:15266
beginWork @ react-dom.development.js:16265
performUnitOfWork @ react-dom.development.js:20285
workLoop @ react-dom.development.js:20326
renderRoot @ react-dom.development.js:20406
performWorkOnRoot @ react-dom.development.js:21363
performWork @ react-dom.development.js:21273
performSyncWork @ react-dom.development.js:21247
interactiveUpdates$1 @ react-dom.development.js:21532
interactiveUpdates @ react-dom.development.js:2268
dispatchInteractiveEvent @ react-dom.development.js:5086
Show 46 more frames
index.js:1437 [React Intl] Cannot format message: "Invariant Violation: [React Intl] An `id` must be provided to format a message.", using message id as fallback.
```

This is solved if we remove from any `List` resource component (`UserList`, ...) the following buttons within `DataGrid`:

- `EditButton`
- `ShowButton`, ... 

It seems that creating a new column with the buttons (`EditButton`, `ShowButton`, ...), leads the `DataGridHeaderCell`, to not have an `id` for react-intl to translate.

#### v2.8.5

- [v2.8.5/packages/ra-core/src/util/FieldTitle.tsx](https://github.com/marmelab/react-admin/blob/v2.8.5/packages/ra-core/src/util/FieldTitle.tsx)
- [v2.8.5/packages/ra-core/src/util/getFieldLabelTranslationArgs.ts](https://github.com/marmelab/react-admin/blob/v2.8.5/packages/ra-core/src/util/getFieldLabelTranslationArgs.ts)

#### v2.6.4

- [v2.6.4/packages/ra-core/src/util/FieldTitle.tsx](https://github.com/marmelab/react-admin/blob/v2.6.4/packages/ra-core/src/util/FieldTitle.tsx)

**Comment by kopax** [comment]
After adding into https://github.com/marmelab/react-admin/blob/v2.8.5/packages/ra-core/src/util/getFieldLabelTranslationArgs.ts#L25

```diff
console.log('esm=====', options);
```

I have tried to access `/user-management/users`.

![image](https://user-images.githubusercontent.com/1866564/58494737-1336e700-8176-11e9-8e3c-e0230fe839c7.png)

Looking at `UserList.js`, it seems that it happen here:

```jsx
        <ShowButton size="sm" />
        <EditButton size="sm" />
        <DeleteButton size="sm" />
```

Adding the `prop.source={"deleted"}` as a test seems to solve the error but it is not expected to have `source` set at this moment.

**Comment by kopax** [comment]
After some testing in the `simple` demo, this is what they have in `getFieldLabelTranslationArgs.ts` :

```bash
options {label: undefined, resource: "posts", source: undefined}
return [""]
```

This is what we have 

```bash
options {label: undefined, resource: "user-management/users", source: undefined}
return [""]
```

This means that this function call produce the expected return. We must have an error somewhere else, or perhaps a missing translate id key.

After some testing, it seems that our `TranslationProvider.js` implementation with react-intl is receiving this empty string (It is expected with the TranslationProvider polyglot), that is invalid value for react-intl translate 

![image](https://user-images.githubusercontent.com/1866564/58496975-3dd76e80-817b-11e9-9d00-3f04b31d219c.png)

**Comment by kopax** [comment]
Related commit allowing an empty string as a translation: https://github.com/marmelab/react-admin/commit/6a687e635f7d78d3322adaa4c19896fa1d9a9e21#diff-9b92e66c935f928c9b0ec3aa9d312e93

**Comment by kopax** [comment]
Solved with https://github.com/yeutech-lab/react-admin-intl/releases/tag/v1.1.4
